# -*- coding: utf-8 -*-
"""train_and_export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wgKw_pAL0z8CDgeoUfwJahY8f7CjzLU

# Roboflow 데이터셋 → YOLOv8 학습 → 구글드라이브로 가중치 내보내기

**Google Colab에서 실행**하는 걸 전제로 작성했습니다.

실행 순서: 위에서부터 셀을 하나씩 순서대로 실행하시면 됩니다 (각 셀 클릭 후 `Shift+Enter`).

런타임 설정: 상단 메뉴 **수정(Edit) → 노트북 설정(Notebook settings)** 에서 **GPU**로 하드웨어 가속기를 설정해두세요. GPU 없이 돌리면 학습이 매우 느립니다.

## 1. 패키지 설치
"""

!pip install -q roboflow ultralytics

"""## 2. 구글드라이브 마운트

학습 완료된 가중치를 저장할 드라이브를 먼저 연결해둡니다. 실행하면 인증 창이 뜨는데, 본인 구글 계정으로 로그인/허용하시면 됩니다.
"""

from google.colab import drive
drive.mount('/content/drive')

# 결과 가중치를 저장할 드라이브 내 폴더 경로 (원하는 이름으로 바꿔도 됩니다)
DRIVE_SAVE_DIR = '/content/drive/MyDrive/vulcan_yolo_results'

import os
os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)
print('드라이브 저장 폴더:', DRIVE_SAVE_DIR)

"""## 3. Roboflow에서 데이터셋 다운로드

**주의:** 아래 `api_key`는 이미 한 번 외부에 노출됐으니, Roboflow 대시보드에서 재발급(regenerate)한 새 키로 교체해서 사용하시는 걸 권장드립니다.
"""

from roboflow import Roboflow

rf = Roboflow(api_key="여기에_재발급받은_API_키_입력")
project = rf.workspace("new-workspace-5u42l").project("vulcan-1eia9")
version = project.version(2)
dataset = version.download("yolov8")

print('데이터셋 다운로드 완료:', dataset.location)

"""## 4. GPU 확인"""

import torch
print('GPU 사용 가능:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU 이름:', torch.cuda.get_device_name(0))

"""## 5. YOLOv8 학습

필요에 따라 `epochs`, `imgsz`, `batch` 값을 조절하세요. 처음엔 기본값으로 한 번 돌려서 베이스라인을 확인하는 걸 추천드립니다.
"""

from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # nano 모델로 시작 (실시간성 중요할 때 추천)

results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    patience=20,       # 20 epoch 동안 개선 없으면 조기 종료
    project="runs/detect",
    name="vulcan_train",
)

print('학습 완료. 결과 폴더:', results.save_dir)

"""## 6. 학습 결과 확인 (선택)"""

from IPython.display import Image, display

results_png = f"{results.save_dir}/results.png"
if os.path.exists(results_png):
    display(Image(filename=results_png))
else:
    print('results.png 를 찾지 못했습니다. 경로 확인:', results.save_dir)

"""## 7. 완료된 가중치(.pt)를 구글드라이브로 내보내기

`best.pt`(검증 성능이 가장 좋았던 가중치)와 `last.pt`(마지막 epoch 가중치)를 함께 복사해둡니다.
"""

import shutil

weights_dir = f"{results.save_dir}/weights"
best_pt = f"{weights_dir}/best.pt"
last_pt = f"{weights_dir}/last.pt"

for src in [best_pt, last_pt]:
    if os.path.exists(src):
        dst = os.path.join(DRIVE_SAVE_DIR, os.path.basename(src))
        shutil.copy(src, dst)
        print(f'복사 완료: {src} -> {dst}')
    else:
        print(f'파일을 찾지 못했습니다: {src}')

# results.png, confusion_matrix.png 등 학습 그래프도 같이 백업하고 싶으면 아래 주석 해제
# for extra_file in ['results.png', 'confusion_matrix.png']:
#     src = f"{results.save_dir}/{extra_file}"
#     if os.path.exists(src):
#         shutil.copy(src, os.path.join(DRIVE_SAVE_DIR, extra_file))

print('\n모든 파일이 드라이브에 저장되었습니다:', DRIVE_SAVE_DIR)

"""## 8. (선택) 저장된 파일 목록 확인"""

print(os.listdir(DRIVE_SAVE_DIR))